### ISSUE TITLE
How to run rspec for this repo

### ISSUE THREAD

**Issue by chrisduong** [sensu-plugins/sensu-plugins-pagerduty#29]
Hi,

I've tried to run Rspec for this repo, but it keep running forever. The command I use is `Rake spec`

>  G/s  pagerduty   master  rake spec
> /Users/cduong/.rubies/ruby-2.1.5/bin/ruby -I/Users/cduong/.gem/ruby/2.1.5/gems/rspec-support-3.5.0/lib:/Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/exe/rspec test/bin/handler-pagerduty_spec.rb test/bin/mutator-pagerduty-priority-override_spec.rb
> 
> ^C
> RSpec is shutting down and will print the summary report... Interrupt again to force quit.
> rake aborted!
> Interrupt:
> /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/rake_task.rb:79:in `system'
> /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/rake_task.rb:79:in`run_task'
> /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/rake_task.rb:96:in `block (2 levels) in define'
> /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/rake_task.rb:94:in`block in define'
> /Users/cduong/.gem/ruby/2.1.5/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
> Tasks: TOP => spec
> (See full trace by running task with --trace)
> error reading event: Input/output error @ io_fread - <STDIN>
> /Users/cduong/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require': cannot load such file -- pagerduty (LoadError)
>     from /Users/cduong/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /Users/cduong/GitHub/sensu-plugins/pagerduty/bin/handler-pagerduty.rb:21:in`<top (required)>'
>     from /Users/cduong/GitHub/sensu-plugins/pagerduty/test/bin/handler-pagerduty_spec.rb:3:in `require_relative'
>     from /Users/cduong/GitHub/sensu-plugins/pagerduty/test/bin/handler-pagerduty_spec.rb:3:in`<top (required)>'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in`block in load_spec_files'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in`load_spec_files'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:100:in `setup'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in`run'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in`invoke'
>     from /Users/cduong/.gem/ruby/2.1.5/gems/rspec-core-3.5.1/exe/rspec:4:in `<main>'

Thanks for reading.

**Comment by chrisduong** [comment]
Hi,

I thought this plugin does not depend on **pagerduty** gem. And it is weird that it does not complain missing Gem while running.

I'm sorry for the noise.
