### ISSUE TITLE
API Request issues, missing api.json??

### ISSUE THREAD

**Issue by mjgorman** [sensu-plugins/sensu-plugins-pagerduty#34]
setting up pagerduty plugin in my new sensu install, getting this error:

```
10/4/2016 3:19:54 PM
{
  "timestamp": "2016-10-04T22:19:54.234034+0000",
  "level": "info",
  "message": "handler output",
  "handler": {
    "type": "pipe",
    "command": "\/etc\/sensu\/handlers\/handler-pagerduty.rb",
    "name": "pagerduty"
  },
  "output": [
    "\/opt\/sensu\/embedded\/lib\/ruby\/gems\/2.3.0\/gems\/sensu-plugin-1.3.0\/lib\/sensu-handler.rb:98:in `api_request': api.json settings not found. (RuntimeError)\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/gems\/2.3.0\/gems\/sensu-plugin-1.3.0\/lib\/sensu-handler.rb:145:in `stash_exists?'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/gems\/2.3.0\/gems\/sensu-plugin-1.3.0\/lib\/sensu-handler.rb:157:in `block (2 levels) in filter_silenced'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/2.3.0\/timeout.rb:91:in `block in timeout'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/2.3.0\/timeout.rb:33:in `block in catch'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/2.3.0\/timeout.rb:33:in `catch'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/2.3.0\/timeout.rb:33:in `catch'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/2.3.0\/timeout.rb:106:in `timeout'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/gems\/2.3.0\/gems\/sensu-plugin-1.3.0\/lib\/sensu-handler.rb:156:in `block in filter_silenced'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/gems\/2.3.0\/gems\/sensu-plugin-1.3.0\/lib\/sensu-handler.rb:154:in `each'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/gems\/2.3.0\/gems\/sensu-plugin-1.3.0\/lib\/sensu-handler.rb:154:in `filter_silenced'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/gems\/2.3.0\/gems\/sensu-plugin-1.3.0\/lib\/sensu-handler.rb:33:in `filter'\n\tfrom \/opt\/sensu\/embedded\/lib\/ruby\/gems\/2.3.0\/gems\/sensu-plugin-1.3.0\/lib\/sensu-handler.rb:56:in `block in <class:Handler>'\n"
  ]
}
```

the config i'm using:

```
{
  "handlers": {
    "pagerduty": {
      "type": "pipe",
      "command": "/etc/sensu/handlers/handler-pagerduty.rb"
    }
  },
  "pagerduty": {
    "api_key": "REDACTED"
  }
}
```

**Comment by eheydrick** [comment]
That error [is raised](https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-handler.rb#L132) if the server config is missing the `api` section. Take a look at your `/etc/sensu/config.json` and see if you have the `api` section. You can also run `/opt/sensu/embedded/bin/sensu-server -P -c /etc/sensu/config.json` to view the parsed configuration.

**Comment by mjgorman** [comment]
@eheydrick  Thanks for the reply. I don't have a config.json, I'm using conf.d folder to load my config, so I used -d instead of -c. I don't have an api section on the server. I am running in docker and have the API server running separately. Is this part of the problem? Should I just duplicate the api settings from the api container to the server container?

**Comment by mjgorman** [comment]
Went ahead and added api config to the server, just pointing at the api container dns. Seems to be working now. Thanks!

**Comment by eheydrick** [comment]
Glad to hear that resolved it!
